# Register settings for CC1125
#     - generated by SmartRF Studio 

sub writeRegisters
{
    my $dev= shift;
    $dev->writeRegister("IOCFG3",0xB0);
    $dev->writeRegister("IOCFG2",0x06);
    $dev->writeRegister("IOCFG1",0xB0);
    $dev->writeRegister("IOCFG0",0x40);
    $dev->writeRegister("SYNC_CFG1",0x08);
    $dev->writeRegister("DEVIATION_M",0xA3);
    $dev->writeRegister("MODCFG_DEV_E",0x0A);
    $dev->writeRegister("DCFILT_CFG",0x1C);
    $dev->writeRegister("FREQ_IF_CFG",0x33);
    $dev->writeRegister("IQIC",0xC6);
    $dev->writeRegister("CHAN_BW",0x10);
    $dev->writeRegister("MDMCFG0",0x05);
    $dev->writeRegister("SYMBOL_RATE2",0x3F);
    $dev->writeRegister("SYMBOL_RATE1",0x75);
    $dev->writeRegister("SYMBOL_RATE0",0x10);
    $dev->writeRegister("AGC_REF",0x20);
    $dev->writeRegister("AGC_CS_THR",0x19);
    $dev->writeRegister("AGC_CFG1",0xA9);
    $dev->writeRegister("AGC_CFG0",0xCF);
    $dev->writeRegister("FIFO_CFG",0x00);
    $dev->writeRegister("SETTLING_CFG",0x03);
    $dev->writeRegister("FS_CFG",0x12);
    $dev->writeRegister("PKT_CFG0",0x20);
    $dev->writeRegister("PKT_LEN",0xFF);
    $dev->writeRegister("IF_MIX_CFG",0x00);
    $dev->writeRegister("FREQOFF_CFG",0x22);
    $dev->writeRegister("FREQ2",0x56);
    $dev->writeRegister("FREQ1",0xEC);
    $dev->writeRegister("FREQ0",0x28);
    $dev->writeRegister("IF_ADC0",0x05);
    $dev->writeRegister("FS_DIG1",0x00);
    $dev->writeRegister("FS_DIG0",0x5F);
    $dev->writeRegister("FS_CAL0",0x0E);
    $dev->writeRegister("FS_DIVTWO",0x03);
    $dev->writeRegister("FS_DSM0",0x33);
    $dev->writeRegister("FS_DVC0",0x17);
    $dev->writeRegister("FS_PFD",0x50);
    $dev->writeRegister("FS_PRE",0x6E);
    $dev->writeRegister("FS_REG_DIV_CML",0x14);
    $dev->writeRegister("FS_SPARE",0xAC);
    $dev->writeRegister("XOSC5",0x0E);
    $dev->writeRegister("XOSC3",0xC7);
    $dev->writeRegister("XOSC1",0x07);
    $dev->writeRegister("PARTNUMBER",0x58);
    $dev->writeRegister("PARTVERSION",0x21);
    $dev->writeRegister("MODEM_STATUS1",0x10);
    $dev->writeRegister("XOSC_TEST1",0x00);
}

$fRegsDefined= 1;
1;
